Feature/authentication
lu-jim/book-tesla pull request #17
Opened 2022-04-10 22:26 UTC by Maclenn77

Hi, @lu-jim :

I configured devise. It tooks a bit longer than expected due to some problems between versions. I tried simple_token_authentication and Doorkeeper gems, however those gems requires Actionpack version lower than 7 and we have the version 7. In consequence, I opted for devise-jwt, that didn't have any conflict with other versions.

I configured the gems following the documentation [here](https://github.com/waiting-for-dev/devise-jwt/wiki/Configuring-devise-for-APIs) and [here](https://github.com/waiting-for-dev/devise-jwt).

Let me know if you found any problem.

Best regards,
JP

2022-04-12 20:33 UTC, lu-jim requested changes
@Maclenn77 
Good job so far!
There are some issues that you still need to work on to go to the next feature but you are almost there!

Please check the comments for more information.

2022-04-12 20:33 UTC, lu-jim commented on app/controllers/v1/sessions_controller.rb
> +      render json: user.as_json(only: %i[id email], status: :created)
At the moment, we are only rendering the user with email. Let's return the jwt authentication token so the user can add it to their requests.

2022-04-12 20:33 UTC, lu-jim commented on db/seeds.rb
> +user1 = User.create!(username: 'Luma', email: 'test@email.com', password: '12345678', password.confirmation: '12345678' )
At the moment, the user1 seed is not properly being created. Let's change the `password.confirmation` to `password_confirmation`

2022-04-13 20:43 UTC, Maclenn77 commented
Hi, @lu-jim :

I did several changes to the authentication tool to return a JWT token. However, there are some problems.

One of them is the devise version with Rails 7. 

There's a **DisabledSessionError when using authenticate_user! api only**, This is a bug reported and with a solution. However, the solution hasn't been added to the last version of Devise.

The problem appears when going to http://localhost:8000/member-data, a route created to test the API. So, maybe we can move on in that part.

When going to http://localhost:8000/users/sign_in, it appears a json file retrieving a message as it's sign_in 

{"message":"You are logged in."}

However, I haven't been able to do other actions even when the routes exists. I guess that it's required the route and the parameter in JSON. I was trying to use Postman to test that part, but I need help to use the tool. 

I was wondering that you weren't able to test the other version because in origins in CORS file, I only allowed Port:3000 in localhost. I change that part and now it allows any origin.

I hope that we can talk a bit in the afternoon about the project.

Greetings,
JP

2022-04-14 16:20 UTC, lu-jim approved these changes
Hello @Maclenn77,
Your feature is : 
### 🥇  Approved 🥇 
## Optional:
Please check the comments below so we can address this in the future.

2022-04-14 16:20 UTC, lu-jim commented on app/controllers/users/registrations_controller.rb
> +    render json: { message: 'Something went wrong.' }
I'm having issues with registration, and as we are not passing through errors, I'm not able to pinpoint the problem. 
![image](https://user-images.githubusercontent.com/59420634/163429323-fe744e5a-e3f9-4118-8bbd-c7ebf7dd9eb9.png)
## 
I used the same parameters on console and registration worked there.
## 
![image](https://user-images.githubusercontent.com/59420634/163429553-085a2431-70e7-46e1-9350-4d18445d3c08.png)


As this is not required at this stage, we can work on it later, but let me know if I'm missing anything, or if there is anything we can do to improve this.

2022-04-14 16:20 UTC, lu-jim commented on config/initializers/cors.rb
> +    origins '*'
This was not the issue before, it was mostly that I expected to see the JWT token within the response. From what I see, the token is within the headers, so this time I was able to locate it.

2022-04-14 19:08 UTC, merged